### ISSUE TITLE
Build branches on pull requests

### ISSUE THREAD

**Issue by charwking** [charwking/movie-club#129]
I don't think the branch builds are running when pull requests are submitted from forked repos. This needs to be corrected.

**Comment by charwking** [comment]
Hmm... this might be the problem:

![image](https://cloud.githubusercontent.com/assets/5176154/9702071/6b81e476-5413-11e5-9c5e-bf4b80d5fef5.png)

I'm going to flip this on and see if that fixes the issue. :stuck_out_tongue:

**Comment by stlcubsfan** [comment]
Please tell me you're at least having a beer whilst doing this.... :beer:

**Comment by charwking** [comment]
Indeed. This evening it's a New Belgium Long Table.

**Comment by charwking** [comment]
Builds are triggering during pull requests now.
