### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by charwking** [charwking/movie-club#2]
We need to figure out what's going to go on the first page that the users see when they browse to `cwking.com/movieclub`. Any thoughts @ttonyan10?

**Comment by ttonyan10** [comment]
hmmm... perhaps a "This week's movie is: ____" section with the time and location, a section to sign in/submit a movie, and a list of past movies? :tv: :tv: :tv:

**Comment by charwking** [comment]
Good ideas. I hope we get all that in the app somewhere, even if it's not on the front page. We'll have to discuss which pieces of information should be public (everyone can see) and which pieces should be private (only people logged in can see). This is going to be awesome!

**Comment by charwking** [comment]
We've discussed this offline and I feel like we've got a good idea of what we want on the landing page. Closing this and we can open new issues as needed.
