### ISSUE TITLE
do some quick UI/UX sketches or wireframes :)

### ISSUE THREAD

**Issue by ttonyan10** [charwking/movie-club#3]

**Comment by ttonyan10** [comment]
1st draft of the logo!! 

![screen shot 2015-05-07 at 1 13 18 pm](https://cloud.githubusercontent.com/assets/6267762/7522460/e29381d6-f4ba-11e4-9310-3f046b6793ab.png)

**Comment by charwking** [comment]
:a:wesome!

**Comment by ttonyan10** [comment]
A little bit of design progress for the home page: 

![movieclubhomemock](https://cloud.githubusercontent.com/assets/6267762/7537100/ad952484-f55b-11e4-92af-a1a8a78cd988.jpg)

Instead of "My Movies" it could say "Theresa's Movies" or "kratscht's movies" etc. Also, I was trying to get clever on the section titles, thinking "The Plot" could be the about movie club section? ikd... just brainstorming... what do you think @charwking?

**Comment by charwking** [comment]
I _really_ like this! I like the logo so much I wish it were bigger on the page. The VHS library turned out awesome, and I think the section titles are a great idea!

**Comment by charwking** [comment]
@ttonyan10 -- I think I remember us talking about renaming the "My Movies" or "Chip's Movies" link to something else because we were thinking about putting other things on that page as well? Do you remember what that name was, or what other things we were going to put on there?

**Comment by ttonyan10** [comment]
hmm... I think I changed it on my local. I will try to push up my branch tonight. I think with some of the less arrangements I will have some merge conflicts though. My fault for not pushing it sooner though. :)

**Comment by charwking** [comment]
Hey @ttonyan10, are we far enough along that we can close this issue, or do we need to keep it open?

**Comment by ttonyan10** [comment]
@charwking I hope you didn't take a PTO day just to work on Movie Club :)
