### ISSUE TITLE
Youtube trailers

### ISSUE THREAD

**Issue by charwking** [charwking/movie-club#82]
Allow each user to submit a link to a youtube trailer for each movie in their list. Show the trailer on the dashboard for the current movie. Allow an admin user to add a trailer to the current movie if it's missing.

**Comment by ttonyan10** [comment]
Ideally look like so: 
![screen shot 2015-06-28 at 9 27 09 pm](https://cloud.githubusercontent.com/assets/6267762/8399908/81fb5c04-1ddc-11e5-9c96-1456f1c61326.png)

**Comment by charwking** [comment]
Added to dev via #122
