### ISSUE TITLE
Update "About our Club" text

### ISSUE THREAD

**Issue by charwking** [charwking/movie-club#87]
We should have some text in the "About our Club" section on the dashboard. Or, alternatively, get rid of the section.

**Comment by ttonyan10** [comment]
How does this sound:

Movie Club began after a lengthy discussion between coworkers about movies we watched, loved, and hated. It was a surprise to learn that many had missed out on what some considered “ the classics”, others were not up to speed with newer releases, and some people had hardly watched any decent movies in their whole life... 

We decided to give ourselves an excuse to watch these flicks and the official Movie Club was born! We started in the old-fashioned way – each submitting one movie on a paper ticket and pulling one ticket out of the box each meeting. The meetings are run like a book club; we acquire the movie with our own resources, watch the movie on our own time, discuss the movie together over lunch, and then draw another movie before we depart. Movie Club began as an every-other week event, but popular vote demanded we draw movies and meet once a week! The first round "original 11" movies are represented in this websites header image. 

We now have a fully-functioning website and over 20 participants! New faces and new movies are always welcome! Please check out and contribute to our gitHub repo (LINK).

**Comment by charwking** [comment]
I like it!

**Comment by natereinhardt** [comment]
Since pm'ing isnt a thing on git hub and i dont know the link to the movie club website. can someone email it to me or message it here? natemreinhardt@gmail.com is my email. :octocat:

**Comment by BrandonCKrueger** [comment]
Email sent!  

Also, @ttonyan10, that looks great!
